### ISSUE TITLE
Can't build bot

### ISSUE THREAD

**Issue by Alexandervelilyaev** [Tulasinathreddy/Multi-TipBot#1]
I did everything according to the instructions
But got the following error:
/home/alex/.local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "tipper.py", line 19, in <module>
    bot = telebot.TeleBot(token=token) 
TypeError: __init__() got an unexpected keyword argument 'token'

Please tell me what am I doing wrong? 
Thanks in advance

**Comment by mrbeandev** [comment]
try this

> `pip install beautifulsoup4 bs4 mysql-connector pyTelegramBotAPI requests telebot urllib3`

after u use this command you can skip the requirements.txt file step

**Comment by Alexandervelilyaev** [comment]
Thanks. This error are solved. But I got the following:
Traceback (most recent call last):
  File "tipper.py", line 19, in <module>
    bot = telebot.TeleBot(token=token) 
TypeError: __init__() got an unexpected keyword argument 'token'

I have provided all data in config.py: token, api_key, wapi_username, 
db_host, db_user, db_pass, db_database

Please help

**Comment by mrbeandev** [comment]
did you import pytelegrambotapi

`pip install pytelegrambotapi`

**Comment by Alexandervelilyaev** [comment]
It helped me. Thank you very much!
